# Generated by Django 5.1 on 2024-08-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0031_alter_link_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tipo',
            field=models.CharField(choices=[('Samplicious', 'Samplicious'), ('Spectrum', 'Spectrum'), ('Cint', 'Cint'), ('Progede', 'Progede'), ('Sample-cube', 'Sample-cube'), ('Invite', 'Invite'), ('Roirocket', 'Roirocket'), ('Internos', 'Internos')], default='Samplicious', max_length=50),
        ),
    ]
